### ISSUE TITLE
For vue.js

### ISSUE THREAD

**Issue by nicolasdezena** [NeriCodec/nativescript-mercadopago-px#1]
Man, this module is only for angular?

I use vue and not build, the CONSOLE ERROR file:///app/vendor.js:138:34: HMR: Can't find variable: PXLifeCycleProtocol show.

**Comment by NeriCodec** [comment]
Sorry, never saw this issue but this plugin should work with vue without problem.

You can show more info please.

**Comment by NeriCodec** [comment]
Close for inactivity
