### ISSUE TITLE
CocoaPods could not find compatible versions for pod "MercadoPagoSDK"

### ISSUE THREAD

**Issue by davidmhHuenei** [NeriCodec/nativescript-mercadopago-px#11]
Hola. Muchas gracias por desarrollar este plugin. En android me anduvo perfecto. Pero en iOS me arroja un error al hacer tns debug ios --emulator:

Installing pods...
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "MercadoPagoSDK":
  In Podfile:
    MercadoPagoSDK (~> 4.28)

Specs satisfying the `MercadoPagoSDK (~> 4.28)` dependency were found, but they required a higher minimum deployment target.
'pod install' command failed.

El problema lo reproduje en el simulador de iphone 8 con ios 13.

Mi package.json tiene las dependencias:
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/theme": "~2.3.3",
    "moment": "^2.26.0",
    "nativescript-algolia": "^1.2.2",
    "nativescript-angular": "~8.21.0",
    "nativescript-appversion": "^1.4.4",
    "nativescript-carousel": "^6.1.1",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-material-bottomnavigationbar": "^3.2.8",
    "nativescript-material-bottomsheet": "^2.5.4",
    "nativescript-mercadopago-px": "^4.0.0",
    "nativescript-pager": "^12.0.0-alpha.8",
    "nativescript-plugin-firebase": "^10.5.2",
    "nativescript-social-share": "^1.6.0",
    "nativescript-ui-listview": "^8.1.2",
    "nativescript-uuid": "git+https://github.com/gdtdpt/nativescript-uuid.git",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.5.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "~8.2.0",
    "nativescript-dev-webpack": "~1.5.1",
    "typescript": "~3.5.3"
  },

nativescript has 6.7.8 
tns-core-modules@6.5.8

El podFile que me genera nativescript contiene:

use_frameworks!

target "buscadornegocios" do
post_install do |installer|
  post_installnativescript_algolia_0 installer
end

# Begin Podfile - /Users/Travis/Documents/proyectos/buscador-negocios/mobile/buscador-negocios/node_modules/nativescript-algolia/platforms/ios/Podfile
pod 'InstantSearchClient', '~> 7.0'

def post_installnativescript_algolia_0 (installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'InstantSearchClient'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end

pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :tag => '2.4.15'
source 'https://github.com/CocoaPods/Specs.git'
pod 'GoogleMaps'
pod 'QBImagePickerController', '~> 3.4.0'
pod 'IQKeyboardManager', '~> 6.2.0'
pod 'MaterialComponents/BottomNavigation+ColorThemer'
pod 'MaterialComponents/BottomSheet'
pod 'CHIPageControl', :git => 'https://github.com/triniwiz/CHIPageControl.git'
**platform :ios, '9.0'**
pod 'Firebase/Core', '~>6.16.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/RemoteConfig'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/DynamicLinks'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'GoogleSignIn', '~> 5.0'
pod 'SAMKeychain', '~> 1.5.3'
pod 'MaterialComponents/schemes/Color'
pod 'MaterialComponents/Ink+ColorThemer'
pod 'MaterialComponents/schemes/Color'

use_frameworks!
pod 'MaterialComponents/Tabs', '~> 94.5'
pod 'MercadoPagoSDK', '~> 4.28'

end

Entonces lo que hice fue (aunque no debería modificar este archivo) modificar la linea:
platform :ios, '9.0'
por:
platform :ios, '11.0' o '10.0'

Con esto me deja de dar el error mencionado, pero cuando corro la app, si hago tap en cualquier input, crashea.
Es como que al actualizar la versión del platform ios el appdelegate no se comporta igual. No se si es correcto modificar esa versión del platform ios o hay que actualizarla y tambien hacer cambios en el plugin.

Desde ya, mil gracias por vuestra ayuda!

**Comment by sebalopezz** [comment]
Buenas tardes, esto sucede porque estas usando el plugin de firebase y requiere minimo iOS 9.0.
Tenes que acceder a node_modules a nativescript-plugin-firebase, plataforms, ios pod y cambiar el mínimo de 9.0 a 10.0

**Comment by sebalopezz** [comment]
Este plugin de mercado pago requiere que todos los demas pidan minimo 10.0, debes modificar todos los que pidan una versión menor y reenplazar por 10.0 minimo

**Comment by sebalopezz** [comment]
Y respecto al input tienes que modificar el app delegate como mencioné en el README.md

**Comment by NeriCodec** [comment]
#6
