### ISSUE TITLE
Error: Validacion de preferencia. (iOS) | Algo salio mal (Android)

### ISSUE THREAD

**Issue by sebalopezz** [NeriCodec/nativescript-mercadopago-px#5]
@NeriCodec please help!
### Which platform(s) does your issue occur on?
- Both 
- iOS 12.2 | iOS 13.5 | Android 10 
- iOS Simulator and Android Real Device via USB

![image](https://user-images.githubusercontent.com/44277483/85231938-c7369000-b3d1-11ea-8b51-c5a3e16ede84.png)

![image](https://user-images.githubusercontent.com/44277483/85231978-1977b100-b3d2-11ea-9d71-cf33253bc963.png)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.4
- Runtime(s): tns-android and tns-ios version 6.5.1
- Plugin(s): "nativescript-mercadopago-px": "^4.0.0",

### Is there any code involved? 
```
methods: {
      crearPreferencia(){
        fetch("https://api.mercadolibre.com/checkout/preferences?access_token="+this.accessToken, {
          method: 'POST',
          headers:{
            'Content-Type': 'application/json',
            'cache-control': 'no-cache'
          },
          body: JSON.stringify({
            "items": [
              {
                "title": "Mi producto",
                "quantity": 1,
                "unit_price": 10
              }
            ]
          })
        })
        .then(res => {
          res.json()
          .then(resp => {
            this.preferenceid = resp.id
          })
        })
      },
      pay() {
        this.mercadopagoPx = new MercadopagoPx();
        this.mercadopagoPx
            .checkout({
                language: "es",
                publicKey: "TEST-3e352e9a-f13c-4451-87cf-994fe4eff45a",
                preferenceId: this.preferenceid
            })
            .then(result => {
                console.log("checkout -> ");
                console.dir(result);
            })
            .catch(error => {
                console.log(error);
            });
      },
```

I think i have a problem with the preferenceID, but if I open the init_point (from the resp inside the crearPreferencia method) URL in my browser it works correctly, so the preferenceID is valid.

**Comment by NeriCodec** [comment]
Hola @sebalopezz debes de pasar el  "currency_id": "ARS", al preference y este debe ser con el que tienes configurado en tu cuenta

**Comment by sebalopezz** [comment]
@NeriCodec gracias por contestar tan rapido! Creo que podemos hablar en español jaja. Actualmente le estoy enviado todos esos datos, y la response de la preferenceID tambien esta completa. No sabes que otra cosa puede ser? A vos te funciona actualmente?

![image](https://user-images.githubusercontent.com/44277483/85233205-f56c9d80-b3da-11ea-9c85-26077905b076.png)

```
fetch("https://api.mercadolibre.com/checkout/preferences?access_token="+this.accessToken, {
          method: 'POST',
          headers:{
            'Content-Type': 'application/json',
            'cache-control': 'no-cache'
          },
          body: JSON.stringify({
            "items": [
              {
                "id": "1234",
                "description": "My super product",
                "title": "Mi producto",
                "quantity": 1,
                "category_id": "12",
                "unit_price": 10
              }
            ],
            "currency_id": "ARS",
            
          })
        })
```

Si entro a ese init_point en mi navegador, tranquilamente funciona y puedo terminar el pago del producto. Es solo en la app que tira el error al querer comenzar el checkout.

**Comment by NeriCodec** [comment]
Si @sebalopezz actualmente lo tengo trabajando, con el ejemplo de muestra también esta bien, cuando ocurre ese error es un problema de generar el preference_id algún campo le está faltando o los keys son incorrectos

**Comment by sebalopezz** [comment]
Genial! Eso del payer me solucionó ahora ya tengo el workflow completo! Muchas gracias.

Por otro lado, otra pregunta, ese mail tiene que ser uno de los mails de prueba que se generan como dice aca [https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/test-integration/](https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/test-integration/) ? O puede ser cualquier mail? Lo que me sucede ahora es que, cuando quiero probar con los datos de la tarjeta de prueba me rechaza..., no se si esta tomando como que es producción o algo. Mi Public Key y Access Token son los del sandbox. 

O hay alguna otra cosa que deba tener en cuenta para probar en Sandbox con las tarjetas de prueba?

**Comment by sebalopezz** [comment]
Listo!  Ya lo pude solucionar... era porque no estaba usando un usuario vendedor de prueba tambien. Ahora ya funciona en sandbox. Muchisimas gracias! Muy bueno tu plugin! Si te parece correcto, despues hago una PR para incluir como usar con Vue en el README o tambien si tengo tiempo una demo-vue.

Gracias! Muy buen trabajo.

**Comment by NeriCodec** [comment]
@sebalopezz Claro está abierto a que se apoye por la comunidad, saludos.
