### ISSUE TITLE
[UIApplicationDelegateImpl window]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by sebalopezz** [NeriCodec/nativescript-mercadopago-px#6]
### Which platform(s) does your issue occur on?
- Both
- iOS 12.2 | iOS 13.5 | Android 10
- iOS Simulator and Android Real Device via USB

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.4
- Runtime(s): tns-android and tns-ios version 6.5.1
- Plugin(s): "nativescript-mercadopago-px": "^4.0.0",

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

En iOS al avanzar a la vista en la que cargas los datos de la tarjeta, una vez que ya seleccionaste la opcion "Tarjeta de credito" la aplicacion se rompe y devuelve este error.

En Android funciona perfecto.

````
file: node_modules/@nativescript/core/application/application.ios.js:312:26: JS ERROR Error: -[UIApplicationDelegateImpl window]: unrecognized selector sent to instance 0x600001e229c0

**Comment by NeriCodec** [comment]
@sebalopezz solo te pasa cuando abres el teclado para ingresar los datos de la tarjeta, o te pasa en cualquier otro input de la aplicación?

**Comment by NeriCodec** [comment]
Una solución simple es agregar esto en tu main.ts

declare var UIResponder,
    UIApplicationDelegate,
    BTAppSwitch,
    UIUserInterfaceStyleLight;
if (app.ios) {
    var appDelegate = UIResponder.extend(
        {
            get window() {
                return this._window;
            },
            set window(aWindow) {
                this._window = aWindow;
            },
        },
        {
            protocols: [UIApplicationDelegate],
        }
    );

    app.ios.delegate = appDelegate;
}

**Comment by sebalopezz** [comment]
Estoy utilizando Nativescript Vue con Javascript (no Typescript)

Tu codigo no me funciono tal cual lo pasaste, pero hice algunas modificaciones a partir de lo que pasaste y logre que funcione:

```
const application = require("tns-core-modules/application");
const MyDelegate = (function (_super) {
    __extends(MyDelegate, _super);
    function MyDelegate() {
        _super.apply(this, arguments);
    }
    MyDelegate = UIResponder.extend(
      {
          get window() {
              return this._window;
          },
          set window(aWindow) {
              this._window = aWindow;
          },
      },
      {
          protocols: [UIApplicationDelegate],
      }
    );

    MyDelegate.ObjCProtocols = [UIApplicationDelegate];
    return MyDelegate;
})(UIResponder);

application.ios.delegate = MyDelegate;
```
Muchas gracias!

En estos dias cuando tenga tiempo, envio una PR para agregar estas cuestiones al README.md
